version: '3.1'

services:

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - 5434:5432
